[package]
name = "cs"
version = "0.1.0"
edition = "2021"
authors = ["Sachin Charakhwal <sachincharakhwal@gmail.com>"]
license = "MIT"
repository = "https://github.com/SCJangra/cs"
readme = "README.md"

[dependencies]
rand = "0.8.5"
